# Generated by Django 2.2.4 on 2021-07-06 22:02

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_show_rel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rel_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
    ]
