# Generated by Django 2.2.4 on 2021-07-06 22:38

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210706_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rel_date',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.date.today),
        ),
    ]
